"""LCM package __init__.py file
This file automatically generated by lcm-gen.
DO NOT MODIFY BY HAND!!!!
"""

from .DVLSensor import DVLSensor
from .IMUSensor import IMUSensor

_sensor_keys_ = {
        "IMUSensor": IMUSensor,
        "DVLSensor": DVLSensor,
    }