"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class IMUSensor(object):
    __slots__ = ["timestamp", "value"]

    def __init__(self):
        self.timestamp = 0.0
        self.value = [ [ 0.0 for dim1 in range(3) ] for dim0 in range(2) ]

    def encode(self):
        buf = BytesIO()
        buf.write(IMUSensor._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">f", self.timestamp))
        for i0 in range(2):
            buf.write(struct.pack('>3f', *self.value[i0][:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != IMUSensor._get_packed_fingerprint():
            raise ValueError("Decode error")
        return IMUSensor._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = IMUSensor()
        self.timestamp = struct.unpack(">f", buf.read(4))[0]
        self.value = []
        for i0 in range(2):
            self.value.append(struct.unpack('>3f', buf.read(12)))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if IMUSensor in parents: return 0
        tmphash = (0xb3bf4699968bb97f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if IMUSensor._packed_fingerprint is None:
            IMUSensor._packed_fingerprint = struct.pack(">Q", IMUSensor._get_hash_recursive([]))
        return IMUSensor._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

