"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class DepthSensor(object):
    __slots__ = ["timestamp", "depth"]

    __typenames__ = ["int64_t", "float"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.timestamp = 0
        self.depth = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(DepthSensor._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qf", self.timestamp, self.depth))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != DepthSensor._get_packed_fingerprint():
            raise ValueError("Decode error")
        return DepthSensor._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = DepthSensor()
        self.timestamp, self.depth = struct.unpack(">qf", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if DepthSensor in parents: return 0
        tmphash = (0xd97fd0672fc2dc8a) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if DepthSensor._packed_fingerprint is None:
            DepthSensor._packed_fingerprint = struct.pack(">Q", DepthSensor._get_hash_recursive([]))
        return DepthSensor._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", DepthSensor._get_packed_fingerprint())[0]

