kind: pipeline
type: docker
name: test


steps:
- name: build_docker
  image: docker:latest
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - docker build -t "${DRONE_REPO}:${DRONE_COMMIT:0:8}" .

- name: install_package
  image: "${DRONE_REPO}:${DRONE_COMMIT:0:8}"
  environment:
    HOLODECKPATH: packages
  depends_on:
  - build_docker
  commands:
  # Find what branch we need to pull from
  - BRANCH_EXISTS=$(git ls-remote --heads https://bitbucket.org/frostlab/HoloOcean-Engine.git ${DRONE_BRANCH} | wc -l)
  - if test "$BRANCH_EXISTS" = "1"; then BRANCH=${DRONE_BRANCH}; else BRANCH=develop; fi
  - echo $BRANCH
  # Install package
  - pip3 install .
  - python3 -c "import holoocean; holoocean.install(\"Ocean\", branch=\"$BRANCH\")"

# iterate through all python versions
- name: py36
  image: "${DRONE_REPO}:${DRONE_COMMIT:0:8}"
  depends_on:
  - install_package
  commands:
  - tox -e py36

- name: py37
  image: "${DRONE_REPO}:${DRONE_COMMIT:0:8}"
  depends_on:
  - install_package
  commands:
  - tox -e py37

- name: py38
  image: "${DRONE_REPO}:${DRONE_COMMIT:0:8}"
  depends_on:
  - install_package
  commands:
  - tox -e py38

- name: py39
  image: "${DRONE_REPO}:${DRONE_COMMIT:0:8}"
  depends_on:
  - install_package
  commands:
  - tox -e py39

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: publish

steps:
- name: pypi_publish
  image: plugins/pypi
  settings:
    username:
      from_secret: pypi_username
    password:
      from_secret: pypi_password

- name: docker_base_publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: frostlab/holoocean
    dockerfile: docker/Dockerfile
    tags:
      - base-${DRONE_TAG}
      - base

- name: docker_ocean_publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: frostlab/holoocean
    dockerfile: docker/Dockerfile_ocean
    tags:
      - ocean-${DRONE_TAG}
      - ocean

- name: docker_latest_publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: frostlab/holoocean
    dockerfile: docker/Dockerfile_latest
    tags:
      - all-${DRONE_TAG}
      - all
      - latest
      
trigger:
  event:
    - tag 