kind: pipeline
type: docker
name: default

steps:
- name: Build Editor
  image: adamrehn/ue4-full:4.22.3
  commands:
  - bash Build/ContinuousIntegration/build_project.sh
  - echo "The commit builds"

- name: Package Project
  image: adamrehn/ue4-full:4.22.3
  commands:
  # TODO Figure out how to clone using gitea credentials
  - git clone https://bitbucket.org/frostlab/holodeck-ocean-worlds.git
  - bash Build/ContinuousIntegration/package_ue4_project.sh
  - echo "The pull request was successfully packaged"

# TODO Figure out uploading to S3 somewhere
   