kind: pipeline
type: docker
name: default

steps:
- name: Build Editor
  image: adamrehn/ue4-full:4.27.2
  commands:
  - bash Build/ContinuousIntegration/build_project.sh
  - echo "The commit builds"

- name: Package Project
  image: adamrehn/ue4-full:4.27.2
  environment:
    USER:
      from_secret: worlds_username
    PASSWORD: 
      from_secret: worlds_password
  commands:
  # git thinks our gitea's SSL certs are suspicious
  - git config --global http.sslverify "false"
  - git clone https://$USER:$PASSWORD@robots.et.byu.edu/gitea/contagon/HoloOcean-Worlds our_worlds
  - bash Build/ContinuousIntegration/package_ue4_project.sh ${DRONE_COMMIT:0:8}
  - echo "The pull request was successfully packaged"

- name: Push to S3
  image: plugins/s3
  settings:
      bucket: holo
      access_key: 
        from_secret: minio_username
      secret_key: 
        from_secret: minio_password
      source: final/*
      strip_prefix: final/
      target: /Ocean/${DRONE_BRANCH}
      path_style: true
      endpoint: http://minio:9000/  

- name: Push Tagged S3
  image: plugins/s3
  settings:
      bucket: holo
      access_key: 
        from_secret: minio_username
      secret_key: 
        from_secret: minio_password
      source: tag/*
      strip_prefix: tag/
      target: /Ocean/${DRONE_TAG}
      path_style: true
      endpoint: http://minio:9000/  
  when:
    event:
      - tag 