"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class LocationSensor(object):
    __slots__ = ["timestamp", "position"]

    __typenames__ = ["int64_t", "float"]

    __dimensions__ = [None, [3]]

    def __init__(self):
        self.timestamp = 0
        self.position = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(LocationSensor._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>3f', *self.position[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != LocationSensor._get_packed_fingerprint():
            raise ValueError("Decode error")
        return LocationSensor._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = LocationSensor()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.position = struct.unpack('>3f', buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if LocationSensor in parents: return 0
        tmphash = (0x211cfac3b0dd5486) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if LocationSensor._packed_fingerprint is None:
            LocationSensor._packed_fingerprint = struct.pack(">Q", LocationSensor._get_hash_recursive([]))
        return LocationSensor._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", LocationSensor._get_packed_fingerprint())[0]

